apiVersion: apps/v1
kind: Deployment
metadata:
  name: oracle
  labels:
    app: testoracle
spec:
  selector:
    matchLabels:
      app: testoracle
  template:
    metadata:
      labels:
        app: testoracle
    spec:
      containers:
        - image: container-registry.oracle.com/database/free:latest-lite
          name: oracle
          env:
            - name: ORACLE_PWD
              value: "Password1!"
          volumeMounts:
            - name: oracledata
              mountPath: /opt/oracle/oradata
      volumes:
        - name: oracledata
          persistentVolumeClaim:
            claimName: pv0005-volclaim
---
apiVersion: v1
kind: Service
metadata:
  name: testoracle
spec:
  ports:
    - port: 1521
      targetPort: 1521
  selector:
    app: testoracle
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv0005
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 100Mi
  hostPath:
    path: /data/pv0005/
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pv0005-volclaim
spec:
  resources:
    requests:
      storage: 100Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
