apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.federatedNode.port }}
      name: http
      targetPort: {{ .Values.federatedNode.port }}
      protocol: TCP
  selector:
    app: flask
