{{ if .Values.create_db_deployment }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-internal
  namespace: {{ .Release.Namespace }}
  labels:
    app: postgres
spec:
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - image: postgres:13-alpine
          name: db-internal
          env:
            - name: POSTGRES_DB
              value: {{ .Values.db.name | quote }}
            - name: POSTGRES_USER
              value: {{ include "dbUser" . }}
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{.Values.db.secret.name}}
                  key: {{.Values.db.secret.key}}
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: db-volclaim
{{ end }}
