apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-config
  namespace: {{ .Values.namespaces.keycloak }}
data:
  KEYCLOAK_ADMIN: admin
  KC_DB_URL_HOST: {{ .Values.db.host | default (print "db." .Release.Namespace ".svc.cluster.local") | quote }}
  KC_DB: postgres
  KC_DB_URL_PORT: {{ .Values.db.port | default "5432" | quote }}
  KC_DB_URL_DATABASE: fn_{{ .Values.db.name | default "kc_db" }}
  KC_DB_USERNAME: {{ .Values.db.user | default "admin" | quote }}
  KEYCLOAK_TOKEN_LIFE: {{ .Values.token.life | default 2592000 | quote }}
  KEYCLOAK_NAMESPACE: {{ .Values.namespaces.keycloak }}
  KEYCLOAK_HOSTNAME: {{ .Values.ingress.host }}
  # PROXY_ADDRESS_FORWARDING: true
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-config
  namespace: {{ .Release.Namespace }}

data:
  KEYCLOAK_ADMIN: admin
  KC_DB_URL_HOST: {{ .Values.db.host | default (print "db." .Release.Namespace ".svc.cluster.local") | quote }}
  KC_DB_USERNAME: {{ .Values.db.user | default "admin" | quote }}
