apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name | lower }}-ingress-nginx-custom-add-headers
  namespace: {{ index .Values "ingress-nginx" "namespaceOverride" }}
  labels:
    {{ template "defaultLabels" . }}
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/resource-policy: keep
    {{ template "defaultAnnotations" . }}
data:
    strict-transport-security: "max-age=63072000"
    content-security-policy: "default-src 'self' https: ; connect-src 'self' {{ include "cspDomainsSpace" . }}; frame-ancestors: 'self'; script-src 'unsafe-inline'; script-src-elem 'unsafe-inline' https:; img-src https:  data:"
    referrer-policy: "strict-origin"
    permission-policy: "src"
    x-content-type-options: "application/json"
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ .Release.Name | lower }}-ingress-nginx-controller
  namespace: {{ index .Values "ingress-nginx" "namespaceOverride" }}
data:
  add-headers: {{ index .Values "ingress-nginx" "namespaceOverride" }}/{{ .Release.Name | lower }}-ingress-nginx-custom-add-headers
  allow-snippet-annotations: 'true'
