apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: shared-results
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
volumeBindingMode: WaitForFirstConsumer
{{- if .Values.storage.local }}
provisioner: Local
{{- else if .Values.storage.azure }}
provisioner: disk.csi.azure.com
parameters:
  skuname: Premium_LRS
{{- else if .Values.storage.aws }}
provisioner: efs.csi.aws.com
parameters:
  provisioningMode: efs-ap
  fileSystemId: {{ include "awsStorageAccount" . }}
  directoryPerms: "777"
{{- else if .Values.storage.nfs }}
provisioner: {{ .Values.storage.nfs.provisioner }}
mountOptions:
  - hard
{{- end }}
